@minimal_api_HostAddress = http://localhost:5137

GET {{minimal_api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{minimal_api_HostAddress}}
Accept: application/json

###
POST {{minimal_api_HostAddress}}/login
Content-Type: application/json

{
  "Email": "Alexandre@admin.com",
  "Password": "admin123"
 
}

###